### ISSUE TITLE
Dockerfile cant build until finish, error on pip install catkin_tools

### ISSUE THREAD

**Issue by araafario** [dortmans/simatch-docker#1]
The error generated:

#7 [ 4/14] RUN pip install catkin_tools
#7 sha256:e4bae04f0a0cb69e8eae6695eae80af22243e3dfedc16774fc7c2b3d4a81a3db
#7 0.520 Downloading/unpacking catkin-tools
#7 0.886   Cannot fetch index base URL https://pypi.python.org/simple/
#7 1.046   Could not find any downloads that satisfy the requirement catkin-tools
#7 1.046 Cleaning up...
#7 1.046 No distributions at all found for catkin-tools
#7 1.047 Storing debug log for failure in /root/.pip/pip.log
#7 ERROR: executor failed running [/bin/sh -c pip install catkin_tools]: exit code: 1

Anyone having the same problem as me ?

**Comment by littleBu0210** [comment]
is catkin-tools not the catkin_tools,chage the Dokerfile can solve the problem

**Comment by araafario** [comment]
> is catkin-tools not the catkin_tools,chage the Dokerfile can solve the problem

Thank you man. Three years late but I do appreciate.
